#pragma once

enum SHADER_TYPE {
    SHADER_DEFAULT = 0,
    SHADER_UNLIT,
    SHADER_UNLIT_NO_MATERIAL,
    SHADER_NOISE,
    SHADER_NOISE_CIRCLE,
    SHADER_BLURX,
    SHADER_BLURY,
    SHADER_RENDERING_TEXTURE,
    SHADER_ENEMY,
    SHADER_ENVIRONMENT_MAPPING,
    SHADER_ENVIRONMENT_MAPPING_SELECT,
};

enum TEXTURE_INDEX{
    TEXTURE_INDEX_DIFFUSE = 0,
    TEXTURE_INDEX_NORMAL,
    TEXTURE_INDEX_ENVIRONMENT,
    TEXTURE_INDEX_MAX
};
