#pragma once

enum SHADER_TYPE {
    SHADER_DEFAULT,
    SHADER_UNLIT,
    SHADER_UNLIT_NO_MATERIAL,
    SHADER_TEST,
    SHADER_BLURX,
    SHADER_BLURY,
    SHADER_RENDERING_TEXTURE,
    SHADER_ENEMY,
};
